server:
  port: ${PORT:8082}

spring:
  application:
    name: operador-service

  datasource:
    url: jdbc:mysql://monorail.proxy.rlwy.net:27601/operador
    username: root
    password: KJCgKEczAzTmbVriQjoqukpDnGLWTtgg
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

#eureka:
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    service-url:
#      defaultZone:  ${EUREKA_URL:http://localhost:8761/eureka}
#  instance:
#    preferIpAddress: false
#    hostname: ${HOSTNAME:localhost}

orderProduct:
  url: https://unirsoft-gateway-production.up.railway.app/buscador-service/api/peliculas
  # https://unirsoft-gateway-production.up.railway.app/buscador-service/api/peliculas
  #https://unirsoft-buscador-production.up.railway.app/api/peliculas
  #https://buscador-service/api/peliculas/%s